name: CI Workflow

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image for the runner

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use Python 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure to include pytest in your requirements

    - name: Run pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q  # Run pytest with specific 
